# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
    # - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: ${{ github.repository_owner }}
#           gif_out_path: ./assets/github-contribution-grid-snake.gif
#           svg_out_path: ./assets/github-contribution-grid-snake.svg
          outputs: |
            ./assets/github-snake.svg
            ./assets/github-snake-dark.svg?palette=github-dark
            ./assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Upload to repo
        run: |
          git config --global user.email "emdadul.haque@augmedix.com"
          git config --global user.name "Augmedix Rafat"
          git add .
          git commit -m "chore: :+1: image snake"
          git push --force
